####################################################
# ------------------- Config --------------------- #
####################################################

# Permissions:
# shopkeeperslist.reload - Allows the player to reload the plugin with /shopkeeperslist reload.
# shopkeeperslist.findshops - Allows the player to use the /findshops command.
# shopkeeperslist.teleport - Allows the player to teleport to a shopkeeper by right-clicking on the shopkeeper in the GUI.
# shopkeeperslist.openremotely - Allows the player to open a shopkeeper remotely by left-clicking on the shopkeeper in the GUI.

shopkeeper-display:
  # The name of the shopkeeper item in the GUI
  # {name}      - A placeholder for the custom name a player can give their shopkeeper
  name:
    default-name: "&e&lShopkeeper"
    custom-name: "&e&l{name}"
  # The lore lines
  # {owner}     - The owner of the shopkeeper
  # {world}     - The name of the world the shopkeeper is in
  # {X} {Y} {Z} - The coordinates of the location of the shopkeeper
  # {trades}    - A list of the trades the shopkeeper has (customize under 'trades' in this config)
  lore-lines:
    - "&7Owned by: &a{owner}"
    - "&7Location: &a{world} &7at &aX{X}&7, &aY{Y}&7, &aZ{Z}"
    - ""
    - "&e&lTrades:"
    - "{trades}"
    - ""
    - "&7&o➤ Right-click to &a&oteleport"
    - "&7&o➤ Left-click to &a&oopen remotely"
  # {item}      - The item traded
  # {amount}    - The amount of items
  trades:
    no-trades: "&7No trades found."
    # Format:  {out-of-stock-prefix} {cost-1}   {cost-divider} {cost-2}     {divider} {result}
    # Example: X                     6x emerald +              3x diamond   ->        1x elytra
    trade-format:
      out-of-stock-prefix: "&c&lX&r "
      cost-1: "&a{amount}x {item}&r"
      cost-divider: " &7+&r "
      cost-2: "&a{amount}x {item}&r"
      divider: " &7&l->&e "
      result: "&e{amount}x {item}&r"

# The messages that are sent to the player when /shopkeeperslist or /shopkeeperslist help is executed
help-command-lines:
  - "&7&m-------------&r &e&l{name} &7&m-------------"
  - "&7Version: &e{version}"
  - "&7Author: &e{author}"
  - ""
  - "&e/shopkeeperslist help &7- View this help menu."
  - "&e/findshops &7- Displays a GUI with information about all shopkeepers in your server."
  - "&e/findshops selling [item] &7- Shows a GUI listing shopkeepers that sell the specified item."
  - "&e/findshops buying [item] &7- Displays a GUI listing shopkeepers that buy the specified item."
  - "&e/findshops player [player] &7- Opens a GUI with all shopkeepers owned by the specified player."
  - ""
  - "&7For quick access, use &e/fs &7or &e/shops &7instead of /findshops."
  - "&7&m--------------------------------------------"

# ------------------------------------------------------ #
# |                     Messages                       | #
# ------------------------------------------------------ #

no-permission: "&cYou don't have permission to use this command! You need permission &f{permission}&c."
wrong-usage: "&cWrong usage! Use &f{usage}&c."
only-players: "&cYou must be a player to use this command."

config-reloaded: "&aConfig reloaded!"
on-teleport: "&aTeleported to shopkeeper!"

no-shops-found: "&cNo shopkeepers found."
no-shops-selling: "&cNo shops found selling &f{item}&c."
no-shops-buying: "&cNo shops found buying &f{item}&c."
no-shops-player: "&cNo shops found for player &f{player}&c."

on-unknown-error: "&cAn unknown error occurred. Please check the console for more information."